spring:
  datasource:
    url: jdbc:mysql://localhost:3306/staffflow?useSSL=false&serverTimezone=Europe/Madrid&allowPublicKeyRetrieval=true&sslMode=DISABLED
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Europe/Madrid

server:
  port: 8080

